language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby-9.1.5.0
  - jruby-1.7.26
  - rbx-19mode
services:
  - riak
  - couchdb
  - redis
  - cassandra
  - memcached
  - mongodb
before_install:
  - gem install bundler -v '~> 1.10'
  #- script/install-kyotocabinet
  - sudo apt-get install -qq libtokyocabinet8 libtokyocabinet-dev liblzo2-dev libtdb-dev libleveldb-dev tokyotyrant
  - script/start-services
sudo: false
cache: bundler
before_script:
  - mysql -e 'create database moneta;'
  - mysql -e 'create database moneta_activerecord1;'
  - mysql -e 'create database moneta_activerecord2;'
env:
  matrix:
    - GROUP=1
    - GROUP=2
    - GROUP=3
    - GROUP=4
    - GROUP=5
    - GROUP=6
    - GROUP=7
    - GROUP=8
    - GROUP=9
    - GROUP=10
    - GROUP=unstable
    - GROUP=benchmarks:uniform_small
    - GROUP=benchmarks:uniform_medium
    - GROUP=benchmarks:uniform_large
    - GROUP=benchmarks:normal_small
    - GROUP=benchmarks:normal_medium
    - GROUP=benchmarks:normal_large
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
    - rvm: jruby-1.7.26
    - rvm: rbx-19mode
    - env: GROUP=unstable
script: ruby scripts/travis $GROUP 10
branches:
  only:
    - master
    - travis
